{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c234c7df-b2b0-4e63-b14e-98f9cc5ea610",
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv\n",
    "import os\n",
    "from datetime import datetime\n",
    "from mlflow.deployments import get_deploy_client\n",
    "\n",
    "def calculate_average_with_llm(numbers):\n",
    "    \"\"\"\n",
    "    Calculate the average of a list of numbers by using an LLM through MLflow\n",
    "    \n",
    "    Args:\n",
    "        numbers (list): List of integers to average\n",
    "        \n",
    "    Returns:\n",
    "        float: The calculated average\n",
    "    \"\"\"\n",
    "    # Prepare the prompt for the LLM\n",
    "    numbers_str = ', '.join(map(str, numbers))\n",
    "    prompt = f\"Calculate the average of these numbers: {numbers_str}\"\n",
    "    \n",
    "    # Call the LLM through MLflow\n",
    "    client = get_deploy_client(os.environ['DOMINO_MLFLOW_DEPLOYMENTS'])\n",
    "    response = client.predict(\n",
    "        endpoint=\"chat-gpt4-ja\",\n",
    "        inputs={\"messages\": [{\"role\": \"user\", \"content\": prompt}]}\n",
    "    )\n",
    "    \n",
    "    # Extract the average from the response\n",
    "    # Note: This assumes the LLM will return a number or a response containing the average\n",
    "    # You might need to adjust this parsing based on the actual response format\n",
    "    try:\n",
    "        # Simple extraction - you may need to implement more robust parsing\n",
    "        response_text = response.get('choices', [{}])[0].get('message', {}).get('content', '')\n",
    "        # Extract the number from the response\n",
    "        import re\n",
    "        average_match = re.search(r'(\\d+(\\.\\d+)?)', response_text)\n",
    "        if average_match:\n",
    "            return float(average_match.group(1))\n",
    "        else:\n",
    "            # Fallback to calculating average directly if parsing fails\n",
    "            return sum(numbers) / len(numbers)\n",
    "    except (KeyError, IndexError, ValueError, ZeroDivisionError) as e:\n",
    "        print(f\"Error parsing LLM response: {e}\")\n",
    "        # Fallback to calculating average directly\n",
    "        return sum(numbers) / len(numbers) if numbers else 0\n",
    "\n",
    "def process_csv_and_output_result(csv_filename):\n",
    "    \"\"\"\n",
    "    Read integers from a CSV file, calculate the average using an LLM,\n",
    "    and write it to a text file with the current date/time.\n",
    "    \n",
    "    Args:\n",
    "        csv_filename (str): Path to the CSV file containing integers\n",
    "    \"\"\"\n",
    "    # Get current date/time for both the filename and content\n",
    "    current_datetime = datetime.now()\n",
    "    date_str = current_datetime.strftime(\"%Y-%m-%d %H:%M:%S\")\n",
    "    output_filename = f\"average_{current_datetime.strftime('%Y%m%d_%H%M%S')}.txt\"\n",
    "    \n",
    "    # Read integers from CSV\n",
    "    numbers = []\n",
    "    try:\n",
    "        with open(csv_filename, 'r') as csv_file:\n",
    "            csv_reader = csv.reader(csv_file)\n",
    "            for row in csv_reader:\n",
    "                # Convert each value in the row to an integer and add to numbers list\n",
    "                for value in row:\n",
    "                    if value.strip():  # Skip empty values\n",
    "                        try:\n",
    "                            numbers.append(int(value.strip()))\n",
    "                        except ValueError:\n",
    "                            print(f\"Warning: Skipping non-integer value: '{value}'\")\n",
    "    except FileNotFoundError:\n",
    "        print(f\"Error: File '{csv_filename}' not found.\")\n",
    "        return\n",
    "    except Exception as e:\n",
    "        print(f\"Error reading CSV file: {e}\")\n",
    "        return\n",
    "    \n",
    "    # Check if we have numbers to average\n",
    "    if not numbers:\n",
    "        print(\"No valid numbers found in the CSV file.\")\n",
    "        return\n",
    "    \n",
    "    # Calculate average using LLM\n",
    "    try:\n",
    "        average = calculate_average_with_llm(numbers)\n",
    "    except Exception as e:\n",
    "        print(f\"Error calculating average with LLM: {e}\")\n",
    "        # Fallback to direct calculation\n",
    "        average = sum(numbers) / len(numbers)\n",
    "        print(f\"Falling back to direct calculation: {average}\")\n",
    "    \n",
    "    # Write result to output file\n",
    "    try:\n",
    "        with open(output_filename, 'w') as output_file:\n",
    "            output_file.write(f\"Date: {date_str}\\n\")\n",
    "            output_file.write(f\"Average: {average}\")\n",
    "        print(f\"Results written to {output_filename}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error writing to output file: {e}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    import sys\n",
    "    \n",
    "    # Check command-line arguments\n",
    "    if len(sys.argv) != 2:\n",
    "        print(\"Usage: python script.py <csv_filename>\")\n",
    "        print(\"Example: python script.py data.csv\")\n",
    "        sys.exit(1)\n",
    "    \n",
    "    csv_filename = sys.argv[1]\n",
    "    process_csv_and_output_result(csv_filename)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
