{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "db66a026-a47a-48f0-ad5f-f7e90bb5ae8d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv\n",
    "import sys\n",
    "from datetime import datetime\n",
    "\n",
    "def calculate_average(csv_filename, output_filename, date_str=None):\n",
    "    \"\"\"\n",
    "    Read integers from a CSV file, calculate the average, and write it to a text file\n",
    "    with the provided date at the top.\n",
    "    \n",
    "    Args:\n",
    "        csv_filename (str): Path to the CSV file containing integers\n",
    "        output_filename (str): Path to the output text file\n",
    "        date_str (str): Date string to include at the top of the output file\n",
    "                       If None, today's date will be used\n",
    "    \"\"\"\n",
    "    # Set date to today if not provided\n",
    "    if date_str is None:\n",
    "        date_str = datetime.now().strftime(\"%Y-%m-%d\")\n",
    "    \n",
    "    # Read integers from CSV\n",
    "    numbers = []\n",
    "    try:\n",
    "        with open(csv_filename, 'r') as csv_file:\n",
    "            csv_reader = csv.reader(csv_file)\n",
    "            for row in csv_reader:\n",
    "                # Convert each value in the row to an integer and add to numbers list\n",
    "                for value in row:\n",
    "                    if value.strip():  # Skip empty values\n",
    "                        try:\n",
    "                            numbers.append(int(value.strip()))\n",
    "                        except ValueError:\n",
    "                            print(f\"Warning: Skipping non-integer value: '{value}'\")\n",
    "    except FileNotFoundError:\n",
    "        print(f\"Error: File '{csv_filename}' not found.\")\n",
    "        return\n",
    "    except Exception as e:\n",
    "        print(f\"Error reading CSV file: {e}\")\n",
    "        return\n",
    "    \n",
    "    # Calculate average\n",
    "    if numbers:\n",
    "        average = sum(numbers) / len(numbers)\n",
    "    else:\n",
    "        print(\"No valid numbers found in the CSV file.\")\n",
    "        return\n",
    "    \n",
    "    # Write result to output file\n",
    "    try:\n",
    "        with open(output_filename, 'w') as output_file:\n",
    "            output_file.write(f\"Date: {date_str}\\n\")\n",
    "            output_file.write(f\"Average: {average}\")\n",
    "        print(f\"Results written to {output_filename}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error writing to output file: {e}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    # Check command-line arguments\n",
    "    if len(sys.argv) < 3:\n",
    "        print(\"Usage: python script.py <csv_filename> <output_filename> [date]\")\n",
    "        print(\"Example: python script.py data.csv output.txt 2025-04-16\")\n",
    "        sys.exit(1)\n",
    "    \n",
    "    csv_filename = sys.argv[1]\n",
    "    output_filename = sys.argv[2]\n",
    "    \n",
    "    # Get date from command line if provided\n",
    "    date_str = sys.argv[3] if len(sys.argv) > 3 else None\n",
    "    \n",
    "    calculate_average(csv_filename, output_filename, date_str)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
